Repository ttangu5510/Project_SkyPower, pull requests merged in 2025-06, with the labels that each got.

#8 [Merge] Branch Test
  Assets/LJ2/LJ2_BranchTest.txt
Labels: merge

#9 [Merge] merge to branch test
  Assets/JJY/Test.txt
Labels: merge

#25 [Merge] Daily merge Kyg_RnD to develop
  Assets/KYG/RnD/RnD.txt
Labels: documentation, merge

#31 [Merge] Daily merge YSK_RnD to develop
  Assets/Settings/URP-Balanced.asset
  Assets/Settings/URP-Performant.asset
  Assets/YSK.meta
  Assets/YSK/Rnd.meta
  Assets/YSK/Rnd/Material.meta
  Assets/YSK/Rnd/Material/MapGroundColor.mat
  Assets/YSK/Rnd/Material/MapGroundColor.mat.meta
  Assets/YSK/Rnd/Material/MapObjectColor.mat
  Assets/YSK/Rnd/Material/MapObjectColor.mat.meta
  Assets/YSK/Rnd/Prefabs.meta
  Assets/YSK/Rnd/Prefabs/Stage1.meta
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_1.prefab
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_1.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_2.prefab
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_2.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_3.prefab
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_3.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_4.prefab
  Assets/YSK/Rnd/Prefabs/Stage1/Map_Stage1_4.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage2.meta
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_1.prefab
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_1.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_2.prefab
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_2.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_3.prefab
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_3.prefab.meta
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_4.prefab
  Assets/YSK/Rnd/Prefabs/Stage2/Map_Stage2_4.prefab.meta
  Assets/YSK/Rnd/Scene.meta
  Assets/YSK/Rnd/Scene/RnDScene.unity
  Assets/YSK/Rnd/Scene/RnDScene.unity.meta
  Assets/YSK/Rnd/ScriptableObject.meta
  Assets/YSK/Rnd/ScriptableObject/Stage1.asset
  Assets/YSK/Rnd/ScriptableObject/Stage1.asset.meta
  Assets/YSK/Rnd/ScriptableObject/Stage2.asset
  Assets/YSK/Rnd/ScriptableObject/Stage2.asset.meta
  Assets/YSK/Rnd/Scripts.meta
  Assets/YSK/Rnd/Scripts/AsyncOperation.meta
  Assets/YSK/Rnd/Scripts/AsyncOperation/LoadStageAsync.cs
  Assets/YSK/Rnd/Scripts/AsyncOperation/LoadStageAsync.cs.meta
  Assets/YSK/Rnd/Scripts/ScriptableObjectMethod.meta
  Assets/YSK/Rnd/Scripts/ScriptableObjectMethod/StageData.cs
  Assets/YSK/Rnd/Scripts/ScriptableObjectMethod/StageData.cs.meta
  Assets/YSK/Rnd/Scripts/ScriptableObjectMethod/StageManager.cs
  Assets/YSK/Rnd/Scripts/ScriptableObjectMethod/StageManager.cs.meta
  Assets/YSK/Rnd/Scripts/StateMethod.meta
  Assets/YSK/Rnd/Scripts/StateMethod/GameStateManager.cs
  Assets/YSK/Rnd/Scripts/StateMethod/GameStateManager.cs.meta
  Assets/YSK/Rnd/Scripts/StateMethod/IGameState.cs
  Assets/YSK/Rnd/Scripts/StateMethod/IGameState.cs.meta
  Assets/YSK/Rnd/Scripts/StateMethod/PlayingState.cs
  Assets/YSK/Rnd/Scripts/StateMethod/PlayingState.cs.meta
  Assets/YSK/Test.txt
  Assets/YSK/Test.txt.meta
  ProjectSettings/ProjectSettings.asset
Labels: merge

#28 [Merge] Daily merge JYL_RnD to develop
  Assets/JYL/Rnd/개인 RnD.txt
  README.md
Labels: documentation, merge

#56 [Merge] Daily merge LJ2_Rnd to develop
  Assets/JYL/Rnd.meta
  Assets/KYG/RnD.meta
  Assets/LJ2/DataSaveTest.cs
  Assets/LJ2/DataSaveTest.cs.meta
  Assets/LJ2/IO.meta
  Assets/LJ2/IO/DataSaveController.cs
  Assets/LJ2/IO/DataSaveController.cs.meta
  Assets/LJ2/IO/SaveData.cs
  Assets/LJ2/IO/SaveData.cs.meta
  Assets/LJ2/IO/SaveHandle.cs
  Assets/LJ2/IO/SaveHandle.cs.meta
  Assets/LJ2/Materials.meta
  Assets/LJ2/Materials/Enemy.mat
  Assets/LJ2/Materials/Enemy.mat.meta
  Assets/LJ2/Materials/Player.mat
  Assets/LJ2/Materials/Player.mat.meta
  Assets/LJ2/Materials/bullet.mat
  Assets/LJ2/Materials/bullet.mat.meta
  Assets/LJ2/Prefabs.meta
  Assets/LJ2/Prefabs/LJ2_EnemyTest.prefab
  Assets/LJ2/Prefabs/LJ2_EnemyTest.prefab.meta
  Assets/LJ2/RnD.meta
  Assets/LJ2/RnD/20250620_RnD.txt.meta
  Assets/LJ2/SaveTest.unity
  Assets/LJ2/SaveTest.unity.meta
  Assets/LJ2/UITest.cs
  Assets/LJ2/UITest.cs.meta
  Assets/SaveData.meta
  Assets/SaveData/SaveDataSample.json
  Assets/SaveData/SaveDataSample.json.meta
  Assets/UI Toolkit.meta
  Assets/UI Toolkit/PanelSettings.asset
  Assets/UI Toolkit/PanelSettings.asset.meta
  Assets/UI Toolkit/UnityThemes.meta
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss.meta
Labels: merge

#55 [Merge] Daily merge JYL_RnD to develop
  README.md
Labels: merge

#92 [Merge] JJY_Enemy Daily Merge to Develop Enemy Spawner
  Assets/JJY/Prefab/EnemySpawner.prefab
  Assets/JJY/Prefab/EnemySpawner.prefab.meta
  Assets/JJY/Prefab/FlyEnemy.prefab
  Assets/JJY/Prefab/FlyEnemy.prefab.meta
  Assets/JJY/RnD/250620.txt
  Assets/JJY/RnD/JJY_RnD.txt
  Assets/JJY/RnD/JJY_RnD.txt.meta
  Assets/JJY/Scenes.meta
  Assets/JJY/Scenes/EnemyTestScene.unity
  Assets/JJY/Scenes/EnemyTestScene.unity.meta
  Assets/JJY/Scripts/BulletPatternData/TripleShot.cs
  Assets/JJY/Scripts/Enemy.cs
  Assets/JJY/Scripts/EnemySpawner.cs
  Assets/JJY/Scripts/EnemySpawner.cs.meta
  Assets/JYL/Scenes/Prototype_Player.unity
  Assets/JYL/Scripts/Bullet/BulletController.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: merge

#91 [Merge] Daily merge JYL_RnD to main
  Assets/JJY/Scripts/BulletPatternData/TripleShot.cs
  Assets/JYL/Prefab/Bullets/Bullet3.prefab
  Assets/JYL/Prefab/Bullets/Bullet3.prefab.meta
  Assets/JYL/Prefab/Player_1.prefab
  Assets/JYL/Scenes/Prototype_Player.unity
  Assets/JYL/ScriptableObject/Bullet.meta
  Assets/JYL/Scripts/Bullet/BulletController.cs
  Assets/JYL/Scripts/Bullet/BulletPrefabController.cs
  Assets/JYL/Scripts/Player/PlayerController.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  Project_Design/UML/UML(v0.1).png
  Project_Design/UML/UML(v0.2).png
Labels: documentation, merge

#93 [Merge] Dally merge KYG_Sky_Power to develop
  Assets/KYG/Sky Power/Managers/GameManager.cs
  Assets/KYG/Sky Power/Managers/GameManager.cs.meta
  Assets/KYG/Sky Power/Scene/Test Sky Power.unity
Labels: merge

#106 [Merge] Daily merge LJ2_Charictor1 to develop
  Assets/LJ2/CharictorTest.unity
  Assets/LJ2/LJ2_Test.unity
  Assets/LJ2/Prefabs/CsvBullet.prefab
  Assets/LJ2/Prefabs/CsvBullet.prefab.meta
  Assets/LJ2/Prefabs/OneCharictorTest.prefab
  Assets/LJ2/Prefabs/OneCharictorTest.prefab.meta
  Assets/LJ2/Prefabs/Player_1.prefab
  Assets/LJ2/Prefabs/Player_1.prefab.meta
  Assets/LJ2/Scripts/Charictor/CharictorController.cs
  Assets/LJ2/Scripts/Charictor/CharictorDataTest.cs
  Assets/LJ2/Scripts/Charictor/CharictorDataTest.cs.meta
  Assets/LJ2/Scripts/Charictor/CharictorHasCsv.cs
  Assets/LJ2/Scripts/Charictor/CharictorHasCsv.cs.meta
  Assets/LJ2/Scripts/Charictor/CsvCharictorController.cs
  Assets/LJ2/Scripts/Charictor/CsvCharictorController.cs.meta
  Assets/LJ2/Scripts/Charictor/ParryingTest.cs
  Assets/LJ2/Scripts/Charictor/ParryingTest.cs.meta
  Assets/LJ2/Scripts/Charictor/SecondTest.asset
  Assets/LJ2/Scripts/Charictor/SecondTest.asset.meta
  Assets/LJ2/Scripts/Charictor/TestCharictor.asset
  Assets/LJ2/Scripts/Charictor/TestCharictor.asset.meta
  Assets/LJ2/Scripts/Charictor/UltTest.cs
  Assets/LJ2/Scripts/Charictor/UltTest.cs.meta
  Assets/LJ2/Scripts/Charictor/oneCharictorTest.asset
  Assets/LJ2/Scripts/Charictor/oneCharictorTest.asset.meta
  Assets/LJ2/Scripts/Charictor/sample.asset
  Assets/LJ2/Scripts/Charictor/sample.asset.meta
  Assets/LJ2/Scripts/Charictor/test.asset
  Assets/LJ2/Scripts/Charictor/test.asset.meta
  Assets/LJ2/Scripts/CsvTest.cs
  Assets/LJ2/Scripts/CsvToSO.cs
  Assets/LJ2/Scripts/CsvToSO.cs.meta
  Assets/LJ2/Scripts/IO/Csv.cs
  Assets/LJ2/Scripts/IO/Csv.cs.meta
  Assets/LJ2/Scripts/IO/Csv/SecondTest.csv
  Assets/LJ2/Scripts/IO/Csv/SecondTest.csv.meta
  Assets/LJ2/Scripts/IO/Csv/csvToSO.csv
  Assets/LJ2/Scripts/IO/Csv/oneCharictorTest.csv
  Assets/LJ2/Scripts/IO/Csv/oneCharictorTest.csv.meta
  Assets/LJ2/Scripts/IO/CsvReader.cs
  Assets/LJ2/Scripts/IO/CsvReader.cs.meta
  Assets/LJ2/Scripts/IO/CsvTable.cs
  Assets/LJ2/Scripts/IO/CsvTable.cs.meta
  Assets/LJ2/Scripts/OneCharictorTest.cs
  Assets/LJ2/Scripts/OneCharictorTest.cs.meta
Labels: merge

#123 [Merge] merge hotfix_250627 to develop by merge conflict problem
  Assets/JJY/Scripts/BulletPatternData/EnemyBulletController.cs
  Assets/LJ2/Scripts/Charictor/ParryingTest.cs
  Assets/LJ2/Scripts/Charictor/ParryingTest.cs.meta
Labels: bug, merge

#129 [Merge] Fix merge problem develop_hotfix into develop
  Assets/Design/Map_Background.meta
  Assets/Design/Member/Design_BSH/BSH_Design.unity
  Assets/Design/Member/Design_BSH/New Material.mat
  Assets/Design/Member/Design_BSH/New Material.mat.meta
  Assets/Design/Member/Design_HSW/HSW_Design.unity
  Assets/Design/Member/HSW.meta
  Project_Design/백승헌/전투기획.pptx
Labels: bug, merge

#133 [Merge] Daily merge Kyg_manager to develop
  Assets/KYG/Sky Power/Item.meta
  Assets/KYG/Sky Power/Item/Csv.meta
  Assets/KYG/Sky Power/Item/Csv/ItemCSV.csv
  Assets/KYG/Sky Power/Item/Csv/ItemCSV.csv.meta
  Assets/KYG/Sky Power/Item/CsvToItemSO.cs
  Assets/KYG/Sky Power/Item/CsvToItemSO.cs.meta
  Assets/KYG/Sky Power/Item/ItemData.cs
  Assets/KYG/Sky Power/Item/ItemData.cs.meta
  Assets/KYG/Sky Power/Scene/Test Sky Power.unity
Labels: merge

#134 [Merge] Daily merge JYL_UI_2 to develop
  Assets/JYL/Scenes/aTitleScene_JYL.unity
  Assets/JYL/Scenes/bMainScene_JYL.unity
  Assets/JYL/Scenes/dStageScene_JYL.unity
  Assets/JYL/Scenes/dStageScene_JYL.unity.meta
  Assets/JYL/Scripts/Manager/UIManager.cs
  Assets/JYL/Scripts/UI/HUDPresenter.cs
  Assets/JYL/Scripts/UI/HUDPresenter.cs.meta
  Assets/JYL/Scripts/UI/HomeUI.cs
  Assets/JYL/Scripts/UI/MainPresenter.cs
  Assets/JYL/Scripts/UI/MainPresenter.cs.meta
  Assets/JYL/Scripts/UI/PopUp/EnhancePopUp.cs
  Assets/JYL/Scripts/UI/PopUp/EnhancePopUp.cs.meta
  Assets/JYL/Scripts/UI/PopUp/GameModePopUp.cs
  Assets/JYL/Scripts/UI/PopUp/GameModePopUp.cs.meta
  Assets/JYL/Scripts/UI/PopUp/InvenPopUp.cs
  Assets/JYL/Scripts/UI/PopUp/InvenPopUp.cs.meta
  Assets/JYL/Scripts/UI/PopUp/MenuPopUp.cs
  Assets/JYL/Scripts/UI/PopUp/PartySetPopUp.cs
  Assets/JYL/Scripts/UI/PopUp/PartySetPopUp.cs.meta
  Assets/JYL/Scripts/UI/PopUp/PopUpUI.cs
  Assets/JYL/Scripts/UI/PopUp/SaveCreatePanel.cs
  Assets/JYL/Scripts/UI/PopUp/SaveCreatePanel.cs.meta
  Assets/JYL/Scripts/UI/PopUp/SaveFilePanel.cs
  Assets/JYL/Scripts/UI/PopUp/SaveFilePanel.cs.meta
  Assets/JYL/Scripts/UI/PopUp/SavePanel.cs
  Assets/JYL/Scripts/UI/PopUp/SavePanel.cs.meta
  Assets/JYL/Scripts/UI/PopUp/SavePopUp.cs
  Assets/JYL/Scripts/UI/PopUp/StageInerSelectPopUp.cs
  Assets/JYL/Scripts/UI/PopUp/StageInerSelectPopUp.cs.meta
  Assets/JYL/Scripts/UI/PopUp/StageSelectPopUp.cs
  Assets/JYL/Scripts/UI/PopUp/StageSelectPopUp.cs.meta
  Assets/JYL/Scripts/UI/TitlePresenter.cs
  Assets/Resources/JYL/UI/Canvas_Home.prefab
  Assets/Resources/JYL/UI/Canvas_PopUp.prefab
  Assets/Resources/JYL/UI/EnhancePopUp.prefab
  Assets/Resources/JYL/UI/EnhancePopUp.prefab.meta
  Assets/Resources/JYL/UI/GameModePopUp.prefab
  Assets/Resources/JYL/UI/GameModePopUp.prefab.meta
  Assets/Resources/JYL/UI/InvenPopUp.prefab
  Assets/Resources/JYL/UI/InvenPopUp.prefab.meta
  Assets/Resources/JYL/UI/PartySetPopUp.prefab
  Assets/Resources/JYL/UI/PartySetPopUp.prefab.meta
  Assets/Resources/JYL/UI/SaveCreatePanel.prefab
  Assets/Resources/JYL/UI/SaveCreatePanel.prefab.meta
  Assets/Resources/JYL/UI/SaveFilePanel.prefab
  Assets/Resources/JYL/UI/SaveFilePanel.prefab.meta
  Assets/Resources/JYL/UI/SavePanel.prefab
  Assets/Resources/JYL/UI/SavePanel.prefab.meta
  Assets/Resources/JYL/UI/StageInerSelectPopUp.prefab
  Assets/Resources/JYL/UI/StageInerSelectPopUp.prefab.meta
  Assets/Resources/JYL/UI/StageSelectPopUp.prefab
  Assets/Resources/JYL/UI/StageSelectPopUp.prefab.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: feat
